### ISSUE TITLE
Can we make the distinction between this repo and Whitebox-tools clearer

### ISSUE THREAD

**Issue by jblindsay** [giswqs/whitebox-python#11]
There seems to be some confusion about the nature of this repo. As you are aware, this repo only contains the Python front-end for WhiteboxTools and is not the WhiteboxTools project itself. Is it possible to make this distinction clearer on the homepage so that people don't continue to report issues here rather than at jblindsay/whitebox-tools? I would suggest 1) renaming of this repo to something like whitebox-python, 2) making the fact that this is a frontend only clearer (although I know that it is already there in the description), 3) adding a statement about issuing tool functioning specific errors to the appropriate repository.

**Comment by giswqs** [comment]
Thank you for the suggestion! I have made changes as suggested.
- renamed the repo to 'whitebox-python'
- added an important note at the beginning of the page: 

> This repository is related to the WhiteboxTools Python Frontend only. You can report issues to this repo if you have problems installing this Python package. If you encounter any tool functioning specific errors, please open an issue on Dr. John Lindsay's WhiteboxTools repo.

Renaming a repo might break the links with PyPI, conda-forge, continuous integration (travis-CI, AppVeyor), etc. I will fix those issues later.

**Comment by jblindsay** [comment]
@giswqs Thanks Qiusheng, I suspect this will save you a lot of grief even if the name change is a bit of a pain now.
