### ISSUE TITLE
glibc requirements

### ISSUE THREAD

**Issue by jchollingsworth** [giswqs/whitebox-python#21]
* whitebox version: (latest, as of sept 2020)
* Python version: 3.7
* Operating System: Ubuntu 18.04

### Description

I tried installing the latest version of Whitebox using:
pip install whitebox

It seems to install, but it won't run because I don't have glibc 2.29 ... (I can't even check the version)
error:
./whitebox_tools: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./whitebox_tools)

I'm running GLIBC 2.27... is upgrading to 2.29 really the only way to get whitebox working?

**Comment by giswqs** [comment]
Take a look at this [colab example](https://colab.research.google.com/drive/15j_qNjrjuW-l1eYC19DZRHYbA8jKz4Vg?usp=sharing), which also uses Ubuntu 18.04 and GLIBC 2.27. Everything works fine. Not sure why it did not work on your computer .

**Comment by jchollingsworth** [comment]
Hmmm... ok. Good to know that it should run ok on GLIBC 2.27. I'll investigate further to see if I can get it working.

**Comment by jchollingsworth** [comment]
It's working... I'm not sure what the problem was... maybe a conflict with pytorch(?)... anyhow, it's fixed. Many thanks.

**Comment by giswqs** [comment]
The package does not have any third-party dependencies. Therefore, it should not conflict with pytorch. It is a good practice to create a fresh conda env to avoid potential dependency conflict. Anyway, glad to know that the problem has been resolved.
