### ISSUE TITLE
(QGIS) ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by cefect** [giswqs/whitebox-python#25]
* whitebox version:1.5.1
* Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
* Operating System: Windows 10 64bit

### Description
I'm running the OSGeo pyqgis distribution

`pip install whitebox `

works fine. However, my distribution seems to be missing Tkinter. I believe there is something with QGIS that doesn't let Tkinter run/install. 

Is there  way to change the backend of whitebox? Or another workaround that will let me run the pyqgis AND whitebox API?

`import whitebox`
`ModuleNotFoundError: No module named '_tkinter'`

**Comment by giswqs** [comment]
It works fine on my end. You can also try out the Jupyter frontend https://github.com/giswqs/whiteboxgui

```python
import whitebox
whitebox.Runner()
```
