### ISSUE TITLE
glibc requirements 

### ISSUE THREAD

**Issue by ashleighm136** [giswqs/whitebox-python#26]
* whitebox version: 1.5.1
* Python version: 3.6
* Operating System: CentOS 8 

### Description

It seems to install, but it won't run any functionality.
error:
./whitebox_tools: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./whitebox_tools)

### What I Did

```
print(wbt.license())
./whitebox_tools: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./whitebox_tools)
```

**Comment by giswqs** [comment]
This is a known issue. It is likely that your computer has an older version of glibc. whitebox v1.5.1 was built upon glibc 2.29. You can try installing an older version of whitebox, e.g., `pip install whitebox==1.4.0`. See https://github.com/jblindsay/whitebox-tools/issues/112#issuecomment-891422741
