### ISSUE TITLE
Whiteboxtools in AWS Sagemaker

### ISSUE THREAD

**Issue by geethaganji** [giswqs/whitebox-python#32]
I was able to install whiteboxtools in AWS Sagemaker notebook instance.
When I tried to execute commands:

import whitebox
wbt = whitebox.WhiteboxTools()
print(wbt.tool_help("ElevPercentile")) and
print(wbt.help())

There is no output printed.
Can anyone help me with how to use whiteboxtools and get results in AWS cloud. Thank you in advance.

**Comment by giswqs** [comment]
Closing this for now. Feel free to reopen if you are still experiencing issues.
