### ISSUE TITLE
Documentation for raster_calculator tool

### ISSUE THREAD

**Issue by mgironamata** [giswqs/whitebox-python#33]
* whitebox version: 2.0.0
* Python version: 3.6
* Operating System: Windows 10

### Description

The documentation for the raster_calculator function on the Python frontend does not seem to be correct. It currently reads: "This tool performs a conditional evaluaton (if-then-else) operation on a raster", which is the documentation for the conditional_evaluation tool. This is a very small issue but I thought I would raise it because it has an easy fix. 

Thanks,
Marc

**Comment by giswqs** [comment]
The documentation was generated by WhiteboxTools rather than the whitebox Python package. See https://github.com/jblindsay/whitebox-tools/blob/master/whitebox_tools.py#L8247

Please report the issue at https://github.com/jblindsay/whitebox-tools/issues
