### ISSUE TITLE
LidarIdwInterpolation does not save CRS to output

### ISSUE THREAD

**Issue by arojas314** [giswqs/whitebox-python#41]
* whitebox version: 2.1.2
* Python version: 3.10
* Operating System: Windows 64-bit

### Description

When running the LidarIdwInterpolation function using the Python front end for whitebox, the coordinate reference system (CRS) is not saved to the output .tif file.

### What I Did
Basic command of function was used.

```
    wbt.lidar_idw_interpolation(
        i=f, 
        output=outdir+fname_dem, 
        parameter="elevation", 
        returns="all", 
        resolution=1.0, 
        weight=1.0, 
        radius=5, 
        exclude_cls='3,4,5,6,7,18', 
        minz=None, 
        maxz=None
    )

```

Thanks in advance.

**Comment by giswqs** [comment]
This appears to be an issue with WhiteboxTools. Please open an issue at https://github.com/jblindsay/whitebox-tools/issues
