### ISSUE TITLE
a bug in func (raster_to_vector_lines)

### ISSUE THREAD

**Issue by SonwYang** [giswqs/whitebox-python#44]
### Description

Hello! Mr.WU. When I turn a single pixel wide raster into a line vector, the previously continuous closed shape becomes a broken line segment. How to avoid this problem?

### code
```
from WBT.whitebox_tools import WhiteboxTools

if __name__ == "__main__":
    rasterPath = "/home/BE/results/cq_test_edge.tif"
    outputPath = "/home/BE/results/cq_test_edge4.shp"
    wbt = WhiteboxTools()

    wbt.raster_to_vector_lines(rasterPath, outputPath)
```
![image](https://user-images.githubusercontent.com/48110397/182813385-ba1915c4-e4df-4274-b2cb-605150f3f09c.png)

**Comment by jblindsay** [comment]
I'm afraid that this is expected behaviour given the algorithm used for line vectorization in the tool. This behaviour cannot be modified without swapping out the algorithm for another, which would mean a tool re-write.

**Comment by SonwYang** [comment]
@jblindsay Hello! Do you know another algorithm used for line vectorization in addition to arcpy?

**Comment by giswqs** [comment]
Closing this issue for now as it is related to the WhiteboxTools backend rather than the frontend.
