### ISSUE TITLE
Raster shift in LidarPointStats?

### ISSUE THREAD

**Issue by yurithefury** [giswqs/whitebox-python#45]
* whitebox version: 2.1.4
* Python version: 3.8
* Operating System: Win11/WSL2

### Description

Hi. I used `LidarPointStats` tool through whitebox-python to create a grid with each raster cell representing the number of points. The tool worked fine. However, it looks like the output is either incorrect or shifted (see a screenshot below). Is this the expected behaviour or am I doing something wrong?

### What I Did

```
wbt.lidar_point_stats(
    i=lidar.las, 
    resolution=1.0,
    num_points=True,
    num_pulses=False,
    avg_points_per_pulse=False,
    z_range=False,
    intensity_range=False,
    predom_class=False
)
```

![Layout 1](https://user-images.githubusercontent.com/6628562/188528852-649818fd-bc9a-4be6-b0a1-b5603c38eb0a.png)

**Comment by giswqs** [comment]
This seems an issue with the whitebox-tools backend. You can open an issue at https://github.com/jblindsay/whitebox-tools/issues.
