### ISSUE TITLE
Discontinuous streams

### ISSUE THREAD

**Issue by InsolublePancake** [giswqs/whitebox-python#46]
* whitebox version: 2.1.4
* Python version: 3.8
* Operating System: Scientific Linux (Rocky 8)

### Description

This is probably not an issue with the tools, but am struggling to extract a continuous stream network from a DEM. I've been experimenting with it for some time but have been unable to improve on what I have now, which is 95% of a drainage network, but with intermittent gaps. The gaps occur where the downhill slope flattens off, even though there is still an obvious channel. I'm guessing that issue originates at the breach_depressions_least_cost stage, but I've experimented with the parameters and can't improve on what I have now, which is no good.

![Discontinuous_streams](https://user-images.githubusercontent.com/6304417/194110240-e8d7712a-7d81-497b-a589-7a19b90a9dc4.png)

### What I Did
[dem.zip](https://github.com/giswqs/whitebox-python/files/9717378/dem.zip)

My method is:

breach_depressions_least_cost:    dist=10,     max_cost=100,     min_dist=True,    fill=True, 
d8_flow_accumulation:    out_type="catchment area"
extract_streams:    threshold=3000
	
Regarding the parameters. I've experimented with a wide range of values for breach depressions dist and max_cost. The values I've shown here work for most of the DEM, but still leave gaps in the stream network.

Any help would be appreciated.

Thanks,
Rick

**Comment by giswqs** [comment]
The whitebox package is only a wrapper of WhiteboxTools. It the tool can run and produce results, then it is not a whitebox issue. I would encourage to ask questions at https://groups.google.com/g/whiteboxtools

**Comment by jblindsay** [comment]
There is a known issue with the breach_depressions_least_cost tool in the current version of WhiteboxTools that can result in some small single-cell pits remaining after treatment. I am currently recommending that people do a quick pass with the FillDepressionsWangAndLiu tool after running breaching to ensure that all pits are removed. This will be fixed in the next release of WhiteboxTools, which I am hoping to release in the next two weeks. If you can't wait until then, the fix is already available in Whitebox Workflows for Python.

**Comment by InsolublePancake** [comment]
I have been using these tools for months and had no idea this Google group
existed, thanks for pointing it out!

**Comment by InsolublePancake** [comment]
Ok, that does seem to be the bug I'm getting. I'll try try the other tool
for now and wait for your next update. Thanks

**Comment by InsolublePancake** [comment]
Hi @jblindsay do you have an ETA for this breach derpessions bug fix?
