### ISSUE TITLE
Negative flow path length

### ISSUE THREAD

**Issue by ClaRizzo** [giswqs/whitebox-python#52]
* whitebox version: 2.2.0
* Python version: 3.10.8
* Operating System: Docker Image, python:3.10-slim-bullseye

### Description

Hi, I’m trying to compute the flow length using downslope_flowpath_length function. The tool seems to work, but I have negative lengths as results. Am I doing something wrong? Could you explain what the output represents?
Thank you!

### What I Did

```
wbt.downslope_flowpath_length(flow_dir_catch, flowlength_catch, esri_pntr=True)
```
(I opened the raster in QGIS for convenience) 
Python result:
![image](https://user-images.githubusercontent.com/118991474/203821233-194043a7-c4f0-4067-ac08-c91e1b778880.png)

Expected result:
![image](https://user-images.githubusercontent.com/118991474/203821702-d0b5b5f2-a5d0-4917-8d92-19a275ec30be.png)

**Comment by giswqs** [comment]
This appears to be an issue with the WBT backend. Please open an issue at https://github.com/jblindsay/whitebox-tools/issues
