### ISSUE TITLE
failed to use the mosaic function

### ISSUE THREAD

**Issue by lthough123** [giswqs/whitebox-python#53]
* whitebox version: v 2.2.0
* Python version:3.9
* Operating System: windows 11

Hello Prof. Wu,

I tried to use the mosaic function according to the tutorial https://jblindsay.github.io/wbt_book/tutorials/mosaic.html, and it does not work.

here is the error report:

--output='M:\test\output\NAME_OF_FILE.tif' --method=nn -v --compress_rasters=False

****************************
* Welcome to Mosaic        *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com      *
****************************
Number of tiles: 2
Reading data...
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', whitebox-raster\src\geotiff\mod.rs:797:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I do not know how to solve this problem, can you help me?

Best regards

**Comment by giswqs** [comment]
This appears to be an issue with the WBT backend. Please report an issue at https://github.com/jblindsay/whitebox-tools/issues. Be sure to provide the source code that can reproduce the issue.
